{"uuid":"30609a15-8f1a-4f59-87f1-696cb4135e70","historyId":null,"status":"broken","statusDetails":{"message":"Oops...we found an error preparing this test file:\n\n  cypress\\integration\\testeAutomacaoE2E.feature\n\n","trace":"\n\nError: Webpack Compilation Error\n./cypress/integration/testeAutomacaoE2E.feature 3:10\nModule parse failed: Unexpected token (3:10)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n| Feature: testeAutomacaoE2E\n| \n>     Sendo um visitante do site Projeto de Testes E2E (Web)\n|     Quero poder acessar a sess√£o de albuns de fotos\n|     Para que possa capturar os dados exbidos e salvalos.\n    at handle (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\packages\\server\\node_modules\\@cypress\\webpack-preprocessor\\dist\\index.js:180:23)\n    at finalCallback (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:257:39)\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:306:14\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\Hook.js:154:20)\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:304:22\n    at Compiler.emitRecords (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:499:39)\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:298:10\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:485:14\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\Hook.js:154:20)\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:482:27\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\neo-async\\async.js:2818:7\n    at done (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\neo-async\\async.js:3522:9)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\tapable\\lib\\Hook.js:154:20)\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\webpack\\lib\\Compiler.js:464:33\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\graceful-fs\\graceful-fs.js:143:16\n    at C:\\Users\\adriano.rosa\\AppData\\Local\\Cypress\\Cache\\9.3.1\\Cypress\\resources\\app\\node_modules\\graceful-fs\\graceful-fs.js:61:14\n    at FSReqCallback.oncomplete (node:fs:188:23)\n\nThis occurred while Cypress was compiling and bundling your test code. This is usually caused by:\n\n- A missing file or dependency\n- A syntax error in the file or one of its dependencies\n\nFix the error in your code and re-run your tests."},"stage":"finished","attachments":[],"parameters":[],"labels":[{"name":"suite","value":"testeAutomacaoE2E.feature"}],"links":[],"start":1643673210264,"name":"Oops...we found an error preparing this test file: testeAutomacaoE2E.feature","fullName":"Oops...we found an error preparing this test file: testeAutomacaoE2E.feature","stop":1643673210264}